name: Docker Build, Scout and Push

on:
  push:
    branches:
      - main

jobs:
  build-scout-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t cabsi34/voting-app:${{ github.sha }} -t cabsi34/voting-app:latest ./azure-vote

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: cabsi34/voting-app:latest
          only-severities: critical,high
          exit-code: false

      - name: Push Docker image
        run: |
          docker push cabsi34/voting-app:${{ github.sha }}
          docker push cabsi34/voting-app:latest
